version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - cp handler.py package/
      - cd package
      - zip -r ../lambda.zip .

artifacts:
  files:
    - lambda.zip
    - template.yaml
