version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .

  build:
    commands:
      - zip -r lambda.zip .
      
artifacts:
  files:
    - lambda.zip
    - template.yaml
