AWSTemplateFormatVersion: "2010-09-09"
Description: Full CI/CD Pipeline for Lambda (IAM, Lambda, CodeBuild, Pipeline)

Parameters:
  GitRepo:
    Type: String
    Description: GitHub repository name (owner/repo)

  GitBranch:
    Type: String
    Default: main
    Description: Branch to build from

  GitOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub Personal Access Token for CodePipeline

Resources:

  #######################################
  # S3 BUCKET FOR PIPELINE ARTIFACTS
  #######################################
  ArtifactBucket:
    Type: AWS::S3::Bucket

  #######################################
  # IAM ROLE FOR LAMBDA
  #######################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  #######################################
  # LAMBDA FUNCTION
  #######################################
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Project1Lambda
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: lambda.zip

  #######################################
  # CODEBUILD ROLE
  #######################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess

  #######################################
  # CODEBUILD PROJECT
  #######################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Project1Build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER

  #######################################
  # CODEPIPELINE ROLE
  #######################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  #######################################
  # CODEPIPELINE
  #######################################
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket

      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Select [0, !Split ["/", !Ref GitRepo]]
                Repo: !Select [1, !Split ["/", !Ref GitRepo]]
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitOAuthToken

        - Name: Build
          Actions:
            - Name: BuildLambda
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject

        - Name: Deploy
          Actions:
            - Name: LambdaDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: Lambda
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                FunctionName: !Ref LambdaFunction
                S3Bucket: !Ref ArtifactBucket
                S3Key: lambda.zip

Outputs:
  LambdaName:
    Value: !Ref LambdaFunction
  PipelineName:
    Value: !Ref Pipeline
