AWSTemplateFormatVersion: "2010-09-09"
Description: "Pipeline stack — S3, IAM roles, CodeBuild, and CodePipeline to build & deploy Lambda"

Parameters:
  GitRepo:
    Type: String
    Description: "GitHub repository in format owner/repo (e.g. myuser/project1)"
  GitBranch:
    Type: String
    Default: main
    Description: "GitHub branch to track"
  GitOAuthToken:
    Type: String
    NoEcho: true
    Description: "GitHub Personal Access Token (PAT) with repo + admin:repo_hook scopes"

Resources:

  ################################################################
  # Artifact S3 bucket for pipeline
  ################################################################
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ################################################################
  # IAM Role for Lambda (with DynamoDB full access)
  ################################################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: project1-lambda-exec-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  ################################################################
  # IAM Role for CodeBuild
  ################################################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: project1-codebuild-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess

  ################################################################
  # CodeBuild Project
  ################################################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: project1-build
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables: []
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30

  ################################################################
  # IAM Role for CodePipeline
  ################################################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: project1-codepipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/IAMFullAccess

  ################################################################
  # The CodePipeline itself
  ################################################################
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Select [ 0, !Split [ "/", !Ref GitRepo ] ]
                Repo:  !Select [ 1, !Split [ "/", !Ref GitRepo ] ]
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitOAuthToken
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy
          Actions:
            - Name: DeployWithCloudFormation
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: project1-lambda-stack
                # Template is the template file produced by the build output
                # We refer to the template.yaml inside the BuildOutput artifact
                TemplatePath: BuildOutput::lambda/template.yaml
                # ParameterOverrides is a JSON object string
                # We'll pass LambdaS3Bucket, LambdaS3Key and LambdaRoleArn into the template
                # Use the CodePipeline variable for the artifact location: BuildOutput.ArtifactName references are not usable,
                # so CloudFormation action will use the object (BuildOutput::lambda.zip) referenced in the template; CloudFormation will get the artifact from the pipeline's artifact store.
                ParameterOverrides: >
                  {"LambdaS3Bucket":"#{ArtifactBucketName}","LambdaS3Key":"lambda.zip","LambdaRoleArn":"!Ref LambdaExecutionRole"}
              RunOrder: 1

  ################################################################
  # (Helper) A mapping output isn't strictly required but we'll add outputs
  ################################################################

Outputs:
  ArtifactBucketName:
    Description: "S3 bucket name used for pipeline artifacts"
    Value: !Ref ArtifactBucket

  PipelineName:
    Description: "CodePipeline name"
    Value: !Ref Pipeline

  LambdaExecutionRoleArn:
    Description: "ARN of the role that Lambda will use"
    Value: !GetAtt LambdaExecutionRole.Arn
